/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    PostsList: typeof import('./src/components/PostsList.vue')['default']
    PostsListItem: typeof import('./src/components/PostsListItem.vue')['default']
    PostView: typeof import('./src/components/PostView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parser@7.28.5_embla-carousel@8.6.0_typescript@5.9.3_vite@7.2.7_@types+n_7sg27lcjjk6wz645lw4lth744e/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parser@7.28.5_embla-carousel@8.6.0_typescript@5.9.3_vite@7.2.7_@types+n_7sg27lcjjk6wz645lw4lth744e/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parser@7.28.5_embla-carousel@8.6.0_typescript@5.9.3_vite@7.2.7_@types+n_7sg27lcjjk6wz645lw4lth744e/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parser@7.28.5_embla-carousel@8.6.0_typescript@5.9.3_vite@7.2.7_@types+n_7sg27lcjjk6wz645lw4lth744e/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UContainer: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parser@7.28.5_embla-carousel@8.6.0_typescript@5.9.3_vite@7.2.7_@types+n_7sg27lcjjk6wz645lw4lth744e/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    USkeleton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parser@7.28.5_embla-carousel@8.6.0_typescript@5.9.3_vite@7.2.7_@types+n_7sg27lcjjk6wz645lw4lth744e/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parser@7.28.5_embla-carousel@8.6.0_typescript@5.9.3_vite@7.2.7_@types+n_7sg27lcjjk6wz645lw4lth744e/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
